### ISSUE TITLE
Error: Cannot find module 'node:crypto'

### ISSUE THREAD

**Issue by bagatel** [robinmoisson/staticrypt#174]
Hello,

After running `npm install -g staticrypt` on a pristiine npm environment (Ubuntu 22.04) I get an error when trying to run staticrypt.
Thanks for your help.

```
> staticrypt
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:crypto'
Require stack:
- /usr/local/lib/node_modules/staticrypt/lib/cryptoEngine.js
- /usr/local/lib/node_modules/staticrypt/cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/staticrypt/lib/cryptoEngine.js:1:48)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/staticrypt/lib/cryptoEngine.js',
    '/usr/local/lib/node_modules/staticrypt/cli/index.js'
  ]
}
> npm version
{
  npm: '8.5.1',
  node: '12.22.9',
  v8: '7.8.279.23-node.56',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '2.1.4',
  http_parser: '2.9.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2023c',
  unicode: '14.0'
}

```

**Comment by robinmoisson** [comment]
Hey @bagatel, thanks for reporting with the details of your install.

The latest version of StatiCrypt is 3.x and isn't compatible with node version < 16 . You need to either update your node version to 16+ (the recommended option if you can, that way you get the latest and most secure StatiCrypt version), or downgrade StatiCrypt to 2.x (for ex with `npm i -g staticrypt@2`).

I'll put a friendlier warning error message to StatiCrypt 3.x so that the fix is clearer.

**Comment by bagatel** [comment]
Bonjour @robinmoisson 
Thanks for your help, works fine with node 18 now!
Have a nice day.

**Comment by robinmoisson** [comment]
Great, thanks for letting me know!
